---
title: "timepointA"
author: "Vanessa Dumeaux"
date: "9/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(phyloseq)
library(ggplot2)
library(dplyr)
library(tibble)

# Import rarefied data for species
ps.rarefied.spec <- readRDS ("/home/data/refined/microbiome2brain/microbiome/R/ps.rarefied.spec.rds")

### timepoint A ------
ps.rarefied.spec0 <- subset_samples(ps.rarefied.spec, timepoint == "A")

dist_methods <- unlist(distanceMethodList)[-c(length(unlist(distanceMethodList)), 16)]
# plist0 <- vector("list", length(dist_methods))
# 
# plist0 <- lapply(dist_methods, function(i){
#   print(i)
#     # Calculate distance matrix
#     iDist <- phyloseq::distance(ps.rarefied.spec0, method=i)
#     # Calculate ordination
#     iMDS  <- ordinate(ps.rarefied.spec0, "MDS", distance=iDist)
#     ## Make plot
#     # Don't carry over previous plot (if error, p will be blank)
#     p <- NULL
#     # Create plot, store as temp variable, p
#     p <- plot_ordination(ps.rarefied.spec0, iMDS, color="age_group")
#     # Add title to each plot
#     p <- p + ggtitle(paste("MDS using distance method ", i, sep=""))
#     # Save the graphic to file.
#     return(list(plot=p, dist=iDist))
# })
# names(plist0) = dist_methods
# 
# 
# saveRDS(plist0, "output/plist_timepointA.rds")

plist0 <- readRDS("output/plist_timepointA.rds")

df.plot0 <- lapply(plist0, "[[", "plot")

var <- c("timepoint", "leptin_ng_ml", "calculatedBMI", "waistCircumference_cm",
         "bmi_group", "age_group",
           "VO2max_ml.kg.min", "Wmax_watts",
           "Average_Kcal", "Minimum_kcal", "Maximum_Kcal",
           "Average_Fiber", "Minimum_Fiber", "Maximum_Fiber",
           "Average_kcal_3d","Average_Fiber_3d", "average_protein_g", "average_fat_g", "average_carb_g",
           "Total_Bone_Mass", "Total_Fat_Mass", "Total_Lean_Mass", "Total_Total_Mass", "fat_lean_ratio")


pdf("output/allmeasures_allvar_mds_timepointA.pdf", width = 20, height = 20)
for (i in var){
  df = plyr::ldply(df.plot0, function(x) x$data)
  names(df)[1] <- "distance"
  p = ggplot(df, aes_string(x="Axis.1", y="Axis.2", color=paste0(i)))
  p = p + geom_point(size=3, alpha=0.5)
  p = p + facet_wrap(~distance, scales="free")
  p = p + ggtitle(paste0(i, " - MDS on various distance metrics"))
  print(p)
}
dev.off()


#### BMI
otu <- data.frame(otu_table(ps.rarefied.spec0))
meta <- data.frame(sample_data(ps.rarefied.spec0))

permanova <- vegan::adonis(t(otu) ~ calculatedBMI,
               data = meta, permutations=99, method = "jaccard")
coef <- coefficients(permanova)["calculatedBMI",]
top.coef.bmiA <- coef[rev(order(abs(coef)))[1:10]]
names(top.coef.bmiA) <- data.frame(tax_table(ps.rarefied.spec0), stringsAsFactors = FALSE)$species[rownames(tax_table(ps.rarefied.spec0)) %in% names(top.coef.bmiA)]
pdf("output/top_BMIgroup_timepointA.pdf")
par(mar = c(3, 14, 2, 1))
barplot(sort(top.coef.bmiA), horiz = T, las = 1, main = "Top taxa - BMI group (timepoint A)")
dev.off()


top.coef.bmiA <- coef[rev(order(abs(coef)))[1:20]]

sig <- data.frame(tax_table(ps.rarefied.spec0), stringsAsFactors = FALSE)[rownames(tax_table(ps.rarefied.spec0)) %in% names(top.coef.bmiA),]
count.plot <- reshape2::melt(otu_table(ps.rarefied.spec0)[rownames(sig),])
colnames(count.plot) <- c("speciesID", "rowname", "abundance")
count.plot$speciesID <- as.character(count.plot$speciesID)
meta.plot <- as(sample_data(ps.rarefied.spec0), "data.frame") %>% 
  rownames_to_column() %>% as_tibble()
tax.plot <- as.data.frame(as(tax_table(ps.rarefied.spec0), "matrix"), stringsAsFactors = FALSE) %>% 
  rownames_to_column(var = "speciesID") %>% as_tibble()

df.plot <- left_join(count.plot, meta.plot)
df.plot <- left_join(df.plot, tax.plot)


q <- ggplot(df.plot, aes(x=calculatedBMI, y = log10(abundance)))+
  geom_smooth(method = "lm", alpha = .15, color = "grey", linetype = "dashed") +
  geom_point() +
  facet_wrap(~species, scales = "free", nrow = 4) +
  xlab("BMI (timepointA)") +
  theme_bw()
ggsave("output/bmical_top20_timepointA.pdf", q, width=20, height = 14)


#### VO2max
wunifrac_dist = phyloseq::distance(ps.rarefied.spec0, method="unifrac", weighted=T)
meta <- data.frame(sample_data(ps.rarefied.spec0))

ord <- vegan::dbrda(wunifrac_dist ~ calculatedBMI + VO2max_ml.kg.min , data = meta)
#ord <- vegan::dbrda(wunifrac_dist ~ calculatedBMI + Wmax_watts , data = meta)

anova(ord, by = 'margin')



permanova <- my.adonis(t(otu) ~ calculatedBMI + VO2max_ml.kg.min, phylo = ps.rarefied.spec0,
               data = meta, permutations=99, method = "wunifrac")
coef <- coefficients(permanova)["VO2max_ml.kg.min",]
top.coef.Vo2A <- coef[rev(order(abs(coef)))[1:10]]
names(top.coef.Vo2A) <- data.frame(tax_table(ps.rarefied.spec0), stringsAsFactors = FALSE)$species[rownames(tax_table(ps.rarefied.spec0)) %in% names(top.coef.Vo2A)]
pdf("output/top_VO2max_timepointA.pdf")
par(mar = c(3, 14, 2, 1))
barplot(sort(top.coef.Vo2A), horiz = T, las = 1, main = "Top taxa - VO2max (timepoint A)")
dev.off()

top.coef <- coef[rev(order(abs(coef)))[1:10]]

sig <- data.frame(tax_table(ps.rarefied.spec0), stringsAsFactors = FALSE)[rownames(tax_table(ps.rarefied.spec0)) %in% names(top.coef),]
count.plot <- reshape2::melt(otu_table(ps.rarefied.spec0)[rownames(sig),])
colnames(count.plot) <- c("speciesID", "rowname", "abundance")
count.plot$speciesID <- as.character(count.plot$speciesID)

df.plot <- left_join(count.plot, meta.plot)
df.plot <- left_join(df.plot, tax.plot)

q <- ggplot(df.plot, aes(x=VO2max_ml.kg.min, y = log10(abundance), color = bmi_group))+
  geom_smooth(method = "lm", alpha = .15, color = "grey", linetype = "dashed") +
  geom_point() +
  facet_wrap(~species, scales = "free", nrow = 4) +
  xlab("VO2max, ml/kg/min (timepoint A)") +
  theme_bw()

ggsave("output/vo2max_top10_timepointA.pdf", q, width=20, height = 20)


```
```{r}
### most variable taxa ---
taxdf <- data.frame(tax_table(ps.rarefied.spec0)@.Data, check.names = FALSE, stringsAsFactors = FALSE)
myTaxa <- rownames(taxdf)[taxdf$CV > 1] # select taxa with counts >0

ps.rarefied.spec0.var = prune_taxa(myTaxa, ps.rarefied.spec0)


otu <- data.frame(otu_table(ps.rarefied.spec0.var))
meta <- data.frame(sample_data(ps.rarefied.spec0.var))
wunifrac_dist = phyloseq::distance(ps.rarefied.spec0.var, method="unifrac", weighted=T)

ord <- vegan::dbrda(wunifrac_dist ~ calculatedBMI + VO2max_ml.kg.min , data = meta)
anova(ord, by = 'margin')

permanova <- my.adonis(t(otu) ~ sample_data(ps.rarefied.spec0.var)$calculatedBMI + sample_data(ps.rarefied.spec0.var)$VO2max_ml.kg.min,, phylo=ps.rarefied.spec0.var)

coef <- coefficients(permanova)["sample_data(ps.rarefied.spec0.var)$VO2max_ml.kg.min",]
top.coef.Vo2A <- coef[rev(order(abs(coef)))[1:10]]
names(top.coef.Vo2A) <- data.frame(tax_table(ps.rarefied.spec0.var), stringsAsFactors = FALSE)$species[rownames(tax_table(ps.rarefied.spec0.var)) %in% names(top.coef.Vo2A)]
pdf("output/top_VO2max_timepointA_var.pdf")
par(mar = c(3, 14, 2, 1))
barplot(sort(top.coef.Vo2A), horiz = T, las = 1, main = "Top taxa - VO2max (timepoint A)")
dev.off()

top.coef <- coef[rev(order(abs(coef)))[1:10]]

sig <- data.frame(tax_table(ps.rarefied.spec0.var), stringsAsFactors = FALSE)[rownames(tax_table(ps.rarefied.spec0.var)) %in% names(top.coef),]
count.plot <- reshape2::melt(otu_table(ps.rarefied.spec0.var)[rownames(sig),])
colnames(count.plot) <- c("speciesID", "rowname", "abundance")
count.plot$speciesID <- as.character(count.plot$speciesID)

df.plot <- left_join(count.plot, meta.plot)
df.plot <- left_join(df.plot, tax.plot)

q <- ggplot(df.plot, aes(x=VO2max_ml.kg.min, y = log10(abundance), color = bmi_group))+
  geom_smooth(method = "lm", alpha = .15, color = "grey", linetype = "dashed") +
  geom_point() +
  facet_wrap(~species, scales = "free", nrow = 2) +
  xlab("VO2max, ml/kg/min (timepoint A)") +
  theme_bw()

ggsave("output/vo2max_top10_timepointA_var.pdf", q, width=10)



```

