---
title: "Conn results from Pierre"
author: "Vanessa Dumeaux"
date: "5/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
ses01.rest1 <- list.files("/home/data/refined/microbiome2brain/MRI/micro2brain/txt_firstlvl_beta_seedcorr_Hippocampus",pattern = "Condition001_Source100.txt", full.names = TRUE)

ses01.rest2 <- list.files("/home/data/refined/microbiome2brain/MRI/micro2brain/txt_firstlvl_beta_seedcorr_Hippocampus",pattern = "Condition002_Source100.txt", full.names = TRUE)

ses02.rest1 <- list.files("/home/data/refined/microbiome2brain/MRI/micro2brain/txt_firstlvl_beta_seedcorr_Hippocampus",pattern = "Condition003_Source100.txt", full.names = TRUE)

ses02.rest2 <- list.files("/home/data/refined/microbiome2brain/MRI/micro2brain/txt_firstlvl_beta_seedcorr_Hippocampus",pattern = "Condition004_Source100.txt", full.names = TRUE)

```
```{r}
participants <- c(paste0("E",1:5), paste0("F", 1:2))
sample.names <- c(paste0(participants, "A", 1),
                  paste0(participants, "A", 2),
                  paste0(participants, "B", 1),
                  paste0(participants, "B", 2))

pdata <- data.frame(ses = c(rep("ses01", 14), rep("ses02", 14)),
                    rest = rep(c(rep("rest1", 7), rep("rest2", 7)), 2), 
                    participants = rep(participants, 4), stringsAsFactors = FALSE)
rownames(pdata) <- sample.names

```


```{r}
files <- c(ses01.rest1, ses01.rest2, ses02.rest1, ses02.rest2)
df.zscore <- do.call(cbind,lapply(files, function(x){
  tb <- read.table(x, sep="", fill = TRUE)
  tb <- tb[-c(100:101),]
  tb.vector <- as.vector(as.matrix(t(tb)))
  tb.vector[is.na(tb.vector)] <- 0
  return(tb.vector)
}))

colnames(df.zscore) <- sample.names
```



```{r}
# v1r1 <- do.call(cbind, lapply(ses01.rest1, scan))
# v1r2 <- do.call(cbind, lapply(ses01.rest2, scan))
# v2r1 <- do.call(cbind, lapply(ses02.rest1, scan))
# v2r2 <- do.call(cbind, lapply(ses02.rest2, scan))
# 
# df <- cbind(v1r1, v1r2, v2r1, v2r2)
# colnames(df) <- sample.names
```
```{r}
library(M3C)
rhc.umap <- M3C::umap(df.zscore, labels=as.factor(pdata$participants))
rhc.umap
```
```{r}
require(vegan)

# PCA
pca <- rda(t(df.zscore))

# plot
pdf("output/rda_rhc_SC_zscore.pdf")
plot(pca, type = 'n', display = 'sites')
cols <- c('#7fc97f', '#beaed4', '#fdc086', '#666666', '#386cb0', '#f0027f', '#bf5b17')
points(pca, display='sites', col = cols[as.numeric(as.factor(pdata$participants))], pch = 16)
text(pca, labels=gsub("ses0", "",pdata$ses), pos=3, cex = 0.6)
#ordihull(pca, groups=pdata$participants)
#ordispider(pca, groups = pdata$participants, label = TRUE)
legend( x="topright", 
        legend=unique(pdata$participants), 
        col=cols, box.lty=0, pch=16)
dev.off()

# PerMANOVA - partitioning the euclidean distance matrix by species
set.seed(123)
adonis(t(df.zscore) ~ pdata$participants + pdata$ses + pdata$rest, method='eu')

```
```{r}
library("ggcorrplot")

high.corr <- df > 0.25
high.idx <- apply(high.corr, 1, sum)
sel <- which(high.idx >=28)

corr <- round(cor(df.zscore[sel,]), 1)
head(corr[, 1:6])

p.mat <- cor_pmat(df)
head(p.mat[, 1:4])

ggcorrplot(corr, p.mat = p.mat, hc.order = TRUE,
    type = "lower", insig = "blank")
```


```{r}
sum.zscore <- apply(df.zscore, 2, function(x){
  sum(x[x > 0.25])
})

sum.voxel <- apply(df.zscore, 2, function(x){
  sum(x > 0.25)
})
mean.zscore <- apply(df.zscore, 2, function(x){
  mean(x[x > 0.25])
})


library(ggplot2)
library(dplyr)

df.summary <- pdata
df.summary$sum.zscore <- sum.zscore
df.summary$sum.voxel <- sum.voxel
df.summary$mean.zscore <- mean.zscore


p1 <- df.summary %>%
  ggplot(aes(x=ses, y=sum.zscore)) +
  geom_boxplot() +
  geom_point(aes(color = participants)) +
  geom_line(aes(group=participants, color = participants), linetype = "dashed") +
  facet_wrap(~rest, scales = "free") +
  #scale_color_manual(values = c("#D55E00", "#0072B2")) + 
  theme_minimal() +
  labs(y = "Sum connectivity (zscore > 0.25) hippocampus right") +
  theme(axis.text = element_text(size = 8), legend.text = element_text(size=8), legend.title = element_text(size=8),legend.direction = "vertical")
p1

ggsave("output/totConn_HC_R.pdf", p1)

p2 <- df.summary %>%
  ggplot(aes(x=ses, y=sum.voxel)) +
  geom_boxplot() +
  geom_point(aes(color = participants)) +
  geom_line(aes(group=participants, color = participants), linetype = "dashed") +
  facet_wrap(~rest, scales = "free") +
  #scale_color_manual(values = c("#D55E00", "#0072B2")) + 
  theme_minimal() +
  labs(y = "Sum connectivity (zscore > 0.25) hippocampus right") +
  theme(axis.text = element_text(size = 8), legend.text = element_text(size=8), legend.title = element_text(size=8),legend.direction = "vertical")
p2

ggsave("output/voxelConn_HC_R.pdf", p2)


p3 <- df.summary %>%
  ggplot(aes(x=ses, y=mean.zscore)) +
  geom_boxplot() +
  geom_point(aes(color = participants)) +
  geom_line(aes(group=participants, color = participants), linetype = "dashed") +
  facet_wrap(~rest, scales = "free") +
  #scale_color_manual(values = c("#D55E00", "#0072B2")) + 
  theme_minimal() +
  labs(y = "mean connectivity (zscore > 0.25) hippocampus right") +
  theme(axis.text = element_text(size = 8), legend.text = element_text(size=8), legend.title = element_text(size=8),legend.direction = "vertical")
p3

ggsave("output/meanConn_HC_R.pdf", p3)



```

```{r}
library(dplyr)
df.summary$sampleID <- substr(rownames(df.summary), 1,3)

pd_sum.zscore <- reshape2::dcast(df.summary, sampleID ~ rest, value.var="sum.zscore") %>%
  dplyr::rename(sum.zscore.rest1 = rest1,
                sum.zscore.rest2 = rest2)

pd_sum.voxel <- reshape2::dcast(df.summary, sampleID ~ rest, value.var="sum.voxel") %>%
  dplyr::rename(sum.voxel.rest1 = rest1,
         sum.voxel.rest2 = rest2)

pd_mean.zscore <- reshape2::dcast(df.summary, sampleID ~ rest, value.var="mean.zscore") %>%
  dplyr::rename(mean.zscore.rest1 = rest1,
         mean.zscore.rest2 = rest2)


  
cl <- readRDS("../../data/metadata.rds")

cl <- left_join(cl, pd_sum.zscore)
cl <- left_join(cl, pd_sum.voxel)
cl <- left_join(cl, pd_mean.zscore)

saveRDS(cl, "../../data/metadata.rds")

```

